### PR TITLE
Fixed usage of wrong method

### PR DESCRIPTION
**Pull request by deshankoswatte**
- Fixed wrong method usage in `updateApplication`.

### CODE REVIEW

**Comment by sanjulamadurapperuma** [comment]
@deshankoswatte shall we revert this PR so we can review the issue templates? @yashodgayashan @vikumkbv is it needed? When I merged this it only had the method name change

**Comment by deshankoswatte** [comment]
@yashodgayashan, @sanjulamadurapperuma added the issue templates and the PR got merged with those. Go check them out by going into the issues tab. Sorry since I was a bit too late to mention it in the PR. Review it here and if there's a change I'll make another PR.

**Comment by yashodgayashan** [comment]
It looks good to me.

**Comment by deshankoswatte** [comment]
> It looks good to me.

@sanjulamadurapperuma and @vikumkbv thoughts would be appreciated.

**Pull request merged**
